name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: teampoi/poi
          stage: main
          yaml: >
            name: poi-v2-backend

            app: node@16

            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: DATABASE_URL
                  value: ${{ secrets.DB }}
              ports: "3008"
              install: npm install
              build: npx tsc; npx prisma generate
              start: node dist/index.js
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
